### ISSUE TITLE
Copy and paste as data input

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/RLumShiny#12]
... is there any way to allow copy and paste for input data? For example in a text field or even better into a table?

---
Edit by @tzerk

Tasks:
- [x] Update package dependencies (DESCRIPTION)
- [x] Update NEWS
- [x] Re-write all data input logics as reactiveValues*
- [x] Re-design data input panel

Applications:
- [x] abanico
- [x] doserecovery
- [x] histogram
- [x] KDE
- [x] radialplot
- [x] transformCW 

\* Currently, all applications handle data import within a reactive() environment. When introducing modifiable tables we have two events that update the data (file upload and modifying the table). We hence need define the input data as a value within reactiveValues() and update them with two observeEvent()s.

**Comment by tzerk** [comment]
Certainly possible, I remember the following package that offers this kind of interactivity: https://github.com/jrowen/rhandsontable

Will see what I can do for a future release, just dropping the link here to not forget about it later.

**Comment by tzerk** [comment]
@RLumSK I did some testing and a first implementation of 'rhandsontable'. It works, but haven't tested it thoroughly yet. But is this what you had in mind (input table is modifiable)?

http://canopus.uberspace.de:64230/packages/RLumShiny/inst/shiny/transformCW/

**Comment by RLumSK** [comment]
Very well, precisely what was needed!

**Comment by tzerk** [comment]
@RLumSK Concerning this feature request and also #14 I overhauled the data input and modification options for the histogram app. It now uses `data.table::fread()` to automatically determine the seperator in an uploaded file, hence several options are now removed from the data tab. Instead, you are now presented a modifiable spreadsheed on the data tab. You are now free to upload a file, or to directly copy and paste your data into the table. You can also remove or add new rows...

Please let me know what you think of the re-design before I update all other applications. You can test the updated app here:

http://canopus.uberspace.de:64230/packages/RLumShiny/inst/shiny/histogram/

**Comment by tzerk** [comment]
All relevant applications have been updated and support copy/paste of data in the data input panels. Would be grateful for feedback/bugtesting before I close this issue.
