### ISSUE TITLE
plot_DRTResults() ... input data are not shown in the table 'primary data set'

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/RLumShiny#13]
After importing the data, the data had no been shown the table. For the default test data set
it works (maybe it is not a bug, hard to say).

**Comment by tzerk** [comment]
I am not able to reproduce this issue, as soon as I upload data the tables are updated immediately.

**Comment by RLumSK** [comment]
Ok, maybe this is a local issue, thanks for checking!

**Comment by tzerk** [comment]
Well, only because it works on my machine doesn't mean there must not be a bug anywhere. If you are able to constantly reproduce this bug, please report back.

I myself tested it locally as well as on my shiny server, both were working correctly.

**Comment by RLumSK** [comment]
Actually it does not work on our local shiny sever, therefore I guess that it is a local issue.

**Comment by tzerk** [comment]
Could you please double-check with the link below if you can reproduce the problem?

http://canopus.uberspace.de:64230/packages/RLumShiny/inst/shiny/doserecovery/
